### ISSUE TITLE
Add credits to Buoyancy Basics

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/buoyancy-basics#18] opened 2024-06-10 15:31 UTC

**Comment by samreid** [comment] 2024-08-04 18:55
@DianaTavares can you please recommend the credits for Buoyancy and Buoyancy Basics?  Density is currently written like so:

```ts
  credits: {
    leadDesign: 'Diana L\u00f3pez Tavares, Kelly Lancaster',
    softwareDevelopment: 'Jonathan Olson, Chris Malley (PixelZoom, Inc.), Sam Reid',
    team: 'Wendy Adams, Trish Loeblein, Ariel Paul, Archie Paulson, Kathy Perkins, Noah Podolefsky, Amy Rouinfar, Carl Wieman',
    qualityAssurance: 'Logan Bray, Steele Dalton, Jaron Droder, Brooklyn Lash, Emily Miller, Liam Mulhall, Devon Quispe, Jacob Romero, Nancy Salpepi, Katie Woessner',
    graphicArts: '',
    soundDesign: '',
    thanks: ''
  },
```

**Comment by samreid** [comment] 2024-08-04 20:43
Closing as duplicate of https://github.com/phetsims/density-buoyancy-common/issues/171

**Closed as completed by samreid** 2024-08-04 20:43 UTC
